[tool.ruff]
line-length = 120
target-version = "py311"
extend-exclude = [".git", "venv", "migrations"]
src = ["src"]

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.extend-per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.ruff.format]
docstring-code-format = true
preview = true
