# Generated by Django 4.2.3 on 2023-08-04 14:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe
import mobiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('name', models.CharField(max_length=150, verbose_name='Brand name')),
            ],
            options={
                'ordering': ('created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('model', models.CharField(max_length=150, unique=True, verbose_name='Mobile model')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles', to='mobiles.brand')),
            ],
            options={
                'ordering': ('created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('name', models.CharField(max_length=150, verbose_name='Nationality name')),
            ],
            options={
                'ordering': ('created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('color', models.CharField(max_length=100, verbose_name='Mobile color')),
                ('size', models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Mobile screen size')),
                ('image', models.ImageField(upload_to=mobiles.models.mobile_image_path, verbose_name='Mobile image')),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='mobiles.mobile')),
            ],
            options={
                'ordering': ('created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('price', models.DecimalField(decimal_places=0, max_digits=9, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Variant price')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('date', models.DateField(default=django.utils.datetime_safe.datetime.now, verbose_name='Price date')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='mobiles.variant')),
            ],
            options={
                'ordering': ('created',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mobile',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobiles', to='mobiles.nationality'),
        ),
        migrations.AddField(
            model_name='brand',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='mobiles.nationality'),
        ),
    ]
